const DEFAULT_SETTINGS = {
	MAX_NEW_WORDS: 5,
	MAX_CARDS: 10,
	CARDS_SHOWED: 0,
	NEW_WORDS_SHOWED: 0,
	PROGRESS: {
		GROUP: 0,
		PAGE: 0,
	},

	GROUPS_START: 0,
	GROUPS_END: 5,
	PAGES_START: 0,
	PAGES_END: 29,

	MIN_AMOUNT: 0,

	VERY_OLD_DATE: '01.01.2000 00:04',
	FIELD_USERNAME: 'RSLangUser',
	DEFAULT_USERNAME: 'MIKA',
};

export default DEFAULT_SETTINGS;
