const WORDS_EVENTS = Object.freeze({
	PUSHED_AGAIN: 'AGAIN_WORD',
	PUSHED_EASY: 'EASY_WORD',
	PUSHED_GOOD: 'GOOD_WORD',
	PUSHED_HARD: 'HARD_WORD',
	PUSHED_REMOVE_FROM_DICTIONARY: 'DELETE_FROM_DICTIONARY',
	PUSHED_ADD_TO_DIFFICULT: 'ADD_TO_DIFFICULT',
	PUSHED_SHOW_ANSWER_BUTTON: 'SHOW_ANSWER',
});

export default WORDS_EVENTS;
